language: python
before_install:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in test/.env.enc -out test/.env -d
python:
- '3.7'
install:
- pipenv install
script:
- python3 setup.py install
- pytest
